### ISSUE TITLE
Text justification

### ISSUE THREAD

**Issue by Juris3D** [Jordonbc/UE4_SimpleWindows#5]
![juris_window_display](https://user-images.githubusercontent.com/22710072/52633118-17dbd600-2ecc-11e9-9708-4697394a6861.jpg)
In "Display Advanced Text", if text justification chosen "Left" or "Right", it does that from center of this window, not from right and left sides. So, only "Center" option is usable.
I include pic of my nodes setup. In case maybe i am doing maybe wrong something.

**Comment by Jordonbc** [comment]
I have looked in to this and there does seem to be a bug with the text adjustment, I have found a solution and updated the code responsible for it.

Let me know if you have any more problems with this.
